/**
 * Soundsphere Project (C) 2026
 * Licensed under GPL-3.0 | See git history for contributors
 */

package com.soundsphere.music.ui.screens.auth

/**
 * Length of the verification / password-reset codes issued by the backend.
 *
 * Codes are generated by Supabase Auth (8 digits); keep this in sync with
 * the backend if the code format ever changes.
 */
const val OTP_LENGTH = 8
